pipeline{
    agent{
     node {
      label "nodejs"
      customWorkspace "/tmp/workspace/greeting-service-deployment/greeting-service"
     }
    }
    stages{
        stage("Install dependencies"){
            steps{
                   sh 'printenv'
                   sh 'npm ci'
            }
        }

        stage("Check Style"){
            steps{
                sh "pwd"
                sh "npm run lint"
            }
        }

        stage("Test"){
            steps{
                sh "npm test"
            }
        }
        stage("Deploy"){
            steps{
                sh '''
		   oc project mdnzcl-deploy-strategies
		   oc start-build greeting-service --follow --wait 
		'''
            }
	}

    }
}
