pipeline{
    agent{
        label "nodejs"
    }
    environment {
      WORKSPACE = ${WORKSPACE}/greeting-service
    }
    stages{
        stage("Install dependencies"){
            steps{
                   sh "npm ci"
            }
        }

        stage("Check Style"){
            steps{
                sh "pwd"
                sh "npm run lint"
            }
        }

        stage("Test"){
            steps{
                sh "npm test"
            }
        }
        stage("Deploy"){
            steps{
                sh '''
		   oc project mdnzcl-deploy-strategies
		   oc start-build greeting-service --follow --wait 
		'''
            }
	}

    }
}
